name: Build and Deploy Node.js App to Azure Web App - SENG401team15

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        working-directory: ./frontend  # Set working directory to frontend
        run: |
          npm install
          npm install --save-dev @types/react-resizable
          npm install --save-dev @types/recharts
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          mkdir deploy
          cp -r frontend/build deploy/  # Copy build directory
          cp -r backend deploy/         # Copy backend directory
          cp frontend/package.json deploy/
          cp frontend/package-lock.json deploy/
          zip -r release.zip deploy/    # Zip the deploy directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'SENG401team15'
          slot-name: 'Production'
          package: ./deploy  # Point to the deploy directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9504C250BECC4EACA132DAF0B5DF63B2 }}
